services:
  app:
    image: whalesdmtr/xrates-app
    container_name: xrates-app
    environment:
      DB_HOST: db
      REDIS_HOST: cache
      REDIS_LOCATION: redis://cache:6379/0
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      - backend
    volumes:
      - static_volume:/app/xrates/staticfiles
  db:
    image: postgres:14.18-alpine3.21
    container_name: xrates-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 3s
      retries: 3
  cache:
    image: redis:8.0.3-alpine3.21
    container_name: xrates-cache
    volumes:
      - cache-data:/data
    networks:
      - backend
  nginx:
    image: nginx:1.25
    container_name: xrates-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/xrates/staticfiles
    depends_on:
      - app
    networks:
      - backend

volumes:
  db-data:
  cache-data:
  static_volume:


networks:
  backend:
