name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build: 
    runs-on: ubuntu-latest

    env:
      DB_NAME: xrates
      DB_USER: postgres           
      DB_PASSWORD: postgres       
      DB_HOST: localhost
      DB_PORT: 5432

      REDIS_HOST: localhost
      REDIS_port: 6379
      REDIS_DB: 0
      REDIS_LOCATION: redis://localhost:6379/0

      DJANGO_DEBUG: 0
      DJANGO_SECRET: secret

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up postgres
      uses: ikalnytskyi/action-setup-postgres@v7
      with:
        username: postgres
        password: postgres
        database: xrates
        postgres-version: 14

    - name: Set up redis
      uses: shogo82148/actions-setup-redis@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd xrates
        ./manage.py test
    
