name: Docker Image Registry CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
        echo "DB_NAME=xrates" >> .env
        echo "DB_USER=postgres" >> .env
        echo "DB_PASSWORD=postgres" >> .env
        echo "DB_HOST=localhost" >> .env
        echo "DB_PORT=5432" >> .env

        echo "REDIS_HOST=localhost" >> .env
        echo "REDIS_port=6379" >> .env
        echo "REDIS_DB=0" >> .env
        echo "REDIS_LOCATION=redis://localhost:6379/0" >> .env

        echo "DJANGO_DEBUG=0" >> .env
        echo "DJANGO_SECRET=secret" >> .env

    - name: Check env file
      run: cat .env

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: whalesdmtr
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: whalesdmtr/xrates-app:latest
